# .github/workflows/frontend-e2e.yml
name: Frontend E2E Tests

on:
  push:
    paths:
      - 'frontend/nextjs/**'
  pull_request:
    paths:
      - 'frontend/nextjs/**'

jobs:
  test_e2e:
    name: Run E2E tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend/nextjs
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: frontend/nextjs/package-lock.json
      
      - name: Install dependencies
        run: npm ci
      
      - name: Install Playwright browsers
        run: npx playwright install --with-deps
      
      - name: Run json-server
        run: npm run json-server &
      
      - name: Run Playwright tests
        run: npm run test:e2e
      
      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: playwright-report
          path: frontend/nextjs/playwright-report