### 注册新用户
POST http://localhost:3000/api/authExternal/register
Content-Type: application/json

{
  "email": "test2@test.com",
  "password": "12345678",
  "name": "Test User"
}

### 用户登录，获取 token
# @name login
POST http://localhost:3000/api/authExternal/login
Content-Type: application/json

{
  "email": "test1@test.com",
  "password": "Test01@test"
}
### Get User Profile Request:
@token = {{login.response.body.*}}

### get todo list（需替换 {{token}} 为上一步返回的 token）
GET http://localhost:3000/api/todos
Authorization: Bearer {{token}}

### create TODO
POST http://localhost:3000/api/todos
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "title": "New Todo from http file"
}

### update TODO
PUT http://localhost:3000/api/todos
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "id": "91a4",
  "title": "Updated Todo Title"
}

### Delete TODO
DELETE http://localhost:3000/api/todos/91a4
Authorization: Bearer {{token}}